version: "3.0"
services:
  dealerbear:
    environment:
      RABBITMQ_HOST : rabbitmq
    build:
      context: ./DealerBear
      dockerfile: Dockerfile
    links: 
        - rabbitmq
    depends_on:
        - rabbitmq
  gamebear:
    environment:
      RABBITMQ_HOST : rabbitmq
    build:
      context: ./GameBear
      dockerfile: Dockerfile
    depends_on:
        - rabbitmq
    links: 
        - rabbitmq

  packbear:
    build:
      context: ./PackBear
      dockerfile: Dockerfile
    depends_on:
        - rabbitmq
    links: 
        - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
    container_name: rabbitmq   

  integrationtest:
    environment:
      RABBITMQ_HOST : rabbitmq
    build:
      context: ./IntegrationTests
      dockerfile: Dockerfile
    depends_on:
        - dealerbear
        - gamebear
        - packbear
        - rabbitmq
    links: 
        - rabbitmq

